version: '3.0'

services:
  foo:
    container_name: "benni_capture_sys"
    image: "benni_capture_sys"
    privileged: true
    build:
      context: ./
      dockerfile: ./Dockerfile
    network_mode: "host"
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    ipc: "host"
    volumes: 
      - "/home/benni/catkin_ws/src:/home/benni/catkin_ws/src"
      - "/home/benni/catkin_ws/0_Data/PGR:/home/benni/catkin_ws/0_Data/PGR"
      - "/home/benni/catkin_ws/0_Data/PCAP:/home/benni/catkin_ws/0_Data/PCAP"
      - "/dev/bus/usb:/dev/bus/usb"

