version: '3.0'

services:
  foo:
    container_name: "benni_capture_sys"
    image: "benni_capture_sys"
    build: .
    network_mode: "host"
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    volumes: 
      - "C:\\Users\\benja\\OneDrive\\Master\\Projekt\\master_catkin_workspace\\src:/catkin_ws/src"
      - "C:\\Users\\benja\\OneDrive\\Master\\Projekt\\master_catkin_workspace\\0_Data\\PGR:/catkin_ws/0_Data/PGR"
      - "C:\\Users\\benja\\OneDrive\\Master\\Projekt\\master_catkin_workspace\\0_Data\\PCAP:/catkin_ws/0_Data/PCAP"
    #devices:
      # sharing graphics driver (http://wiki.ros.org/docker/Tutorials/Hardware%20Acceleration#nvidia-docker2)
      # - "/dev/dri:/dev/dri"
      # mounting usb port for sbg imu
      #- "/dev/ttyUSB0:/dev/ttyUSB0"
